name: CD

on:
  pull_request:
    branches: [develop, main]
    types: [closed]

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  release:
    name: Create Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Debug Git Information
        run: |
          echo "Base Branch: ${{ github.event.pull_request.base.ref }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Merge Commit: ${{ github.event.pull_request.merge_commit_sha }}"
          git rev-parse --verify ${{ github.event.pull_request.base.sha }} || echo "Base SHA not found"
          git rev-parse --verify ${{ github.event.pull_request.head.sha }} || echo "Head SHA not found"
          git rev-parse --verify ${{ github.event.pull_request.merge_commit_sha }} || echo "Merge commit not found"
          echo "List of branches:"
          git branch -a

      - name: Check for GCP changes using improved method
        id: gcp_check
        run: |
          # First try with direct git diff
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^modules/gcp/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "GCP changes detected using direct git diff"
          # Fall back to checking files in the pull request
          elif gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' | grep -q "^modules/gcp/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "GCP changes detected using PR files API"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No GCP changes detected"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Azure changes using improved method
        id: azure_check
        run: |
          # First try with direct git diff
          if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "^modules/azure/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Azure changes detected using direct git diff"
          # Fall back to checking files in the pull request
          elif gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' | grep -q "^modules/azure/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Azure changes detected using PR files API"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No Azure changes detected"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get GCP version
        if: steps.gcp_check.outputs.changed == 'true'
        id: gcp_version
        run: |
          if [ -f "modules/gcp/versions.tf" ]; then
            VERSION=$(grep -oP 'module_version\s*=\s*"\K[^"]+' modules/gcp/versions.tf || echo "0.1.0")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            if [ "${{ github.base_ref }}" != "main" ]; then
              echo "version=$VERSION-dev.$(date +%Y%m%d)" >> $GITHUB_OUTPUT
            fi
            echo "Found GCP version: $VERSION"
          else
            echo "GCP versions.tf file not found, using default version"
            echo "version=0.1.0" >> $GITHUB_OUTPUT
            if [ "${{ github.base_ref }}" != "main" ]; then
              echo "version=0.1.0-dev.$(date +%Y%m%d)" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Get Azure version
        if: steps.azure_check.outputs.changed == 'true'
        id: azure_version
        run: |
          if [ -f "modules/azure/versions.tf" ]; then
            VERSION=$(grep -oP 'module_version\s*=\s*"\K[^"]+' modules/azure/versions.tf || echo "0.1.0")
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            if [ "${{ github.base_ref }}" != "main" ]; then
              echo "version=$VERSION-dev.$(date +%Y%m%d)" >> $GITHUB_OUTPUT
            fi
            echo "Found Azure version: $VERSION"
          else
            echo "Azure versions.tf file not found, using default version"
            echo "version=0.1.0" >> $GITHUB_OUTPUT
            if [ "${{ github.base_ref }}" != "main" ]; then
              echo "version=0.1.0-dev.$(date +%Y%m%d)" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Package GCP module
        if: steps.gcp_check.outputs.changed == 'true'
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'terraform-gcp-modules-${{ steps.gcp_version.outputs.version }}.zip'
          directory: 'modules/gcp'

      - name: Package Azure module
        if: steps.azure_check.outputs.changed == 'true'
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'terraform-azure-modules-${{ steps.azure_version.outputs.version }}.zip'
          directory: 'modules/azure'

      - name: Publish GCP package
        if: steps.gcp_check.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-gcp-modules-${{ steps.gcp_version.outputs.version }}
          path: modules/gcp/terraform-gcp-modules-${{ steps.gcp_version.outputs.version }}.zip
          retention-days: 90

      - name: Publish Azure package
        if: steps.azure_check.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-azure-modules-${{ steps.azure_version.outputs.version }}
          path: modules/azure/terraform-azure-modules-${{ steps.azure_version.outputs.version }}.zip
          retention-days: 90

      - name: Create GCP release
        if: steps.gcp_check.outputs.changed == 'true' && github.base_ref == 'main'
        uses: softprops/action-gh-release@v1
        with:
          files: modules/gcp/terraform-gcp-modules-${{ steps.gcp_version.outputs.version }}.zip
          name: GCP Modules ${{ steps.gcp_version.outputs.version }}
          tag_name: gcp-${{ steps.gcp_version.outputs.version }}
          generate_release_notes: true

      - name: Create Azure release
        if: steps.azure_check.outputs.changed == 'true' && github.base_ref == 'main'
        uses: softprops/action-gh-release@v1
        with:
          files: modules/azure/terraform-azure-modules-${{ steps.azure_version.outputs.version }}.zip
          name: Azure Modules ${{ steps.azure_version.outputs.version }}
          tag_name: azure-${{ steps.azure_version.outputs.version }}
          generate_release_notes: true
