name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: modules
